/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SetObjectTags$Params {
  bucket: string;
  document: string;
  tags: {
[key: string]: string;
};
}

export function setObjectTags(http: HttpClient, rootUrl: string, params: SetObjectTags$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, setObjectTags.PATH, 'post');
  if (params) {
    rb.path('bucket', params.bucket, {});
    rb.path('document', params.document, {});
    rb.query('tags', params.tags, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

setObjectTags.PATH = '/api/cloud/tags/bucket/{bucket}/document/{document}';
