/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MinIoInfos } from '../../models/min-io-infos';

export interface UploadMultipleToMinio$Params {
  files: Array<Blob>;
  bucket: string;
}

export function uploadMultipleToMinio(http: HttpClient, rootUrl: string, params: UploadMultipleToMinio$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MinIoInfos>>> {
  const rb = new RequestBuilder(rootUrl, uploadMultipleToMinio.PATH, 'post');
  if (params) {
    rb.query('files', params.files, {});
    rb.path('bucket', params.bucket, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MinIoInfos>>;
    })
  );
}

uploadMultipleToMinio.PATH = '/api/cloud/upload/bucket/{bucket}';
