## This file will be used when the application is running in the 'dev' profile.
## It will extend the application.yml file and override the necessary properties.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget-buddy-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: localhost
    port: 1025
    username: yassir
    password: yassir
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: zBt3o53uUKLSKzd3XH2INcUztVdMk7mPLnOurF70WdZnyDAMLIhRTOGa+AO/V/rwQmZ2Fijd/Dk+gaoWz2OGpQih48K5uDRb8mF/wyZzh+M=
      expiration: 86400000  # 1 day
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
        redirect-url: http://localhost:4200/login
    file:
      upload:
        photos-output-path: ./uploads

server:
  port: 8088
