spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  main:
    allow-bean-definition-overriding: true

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/  # This will be the base path for all the endpoints

cloud-upload:
  endpoint: http://localhost:9000
  accessKey: 7Hhht2JOgDNbZ10e
  secretKey: wxYq2snPyfYO2Cr43MEe4eiDXecTzp0m
  bucket: budget-buddy

