## This file will be used when the application is running in the 'dev' profile.
## It will extend the application.yml file and override the necessary properties.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensestracker
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
