/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOrUpdateContactState } from '../fn/contact-state/create-or-update-contact-state';
import { CreateOrUpdateContactState$Params } from '../fn/contact-state/create-or-update-contact-state';

@Injectable({ providedIn: 'root' })
export class ContactStateService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createOrUpdateContactState()` */
  static readonly CreateOrUpdateContactStatePath = '/contactState/add-contact-state';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrUpdateContactState()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrUpdateContactState$Response(params: CreateOrUpdateContactState$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return createOrUpdateContactState(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrUpdateContactState$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrUpdateContactState(params: CreateOrUpdateContactState$Params, context?: HttpContext): Observable<number> {
    return this.createOrUpdateContactState$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
