/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getTodayQuote } from '../fn/quote/get-today-quote';
import { GetTodayQuote$Params } from '../fn/quote/get-today-quote';
import { QuotesResponse } from '../models/quotes-response';

@Injectable({ providedIn: 'root' })
export class QuoteService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTodayQuote()` */
  static readonly GetTodayQuotePath = '/quote/today-quote';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTodayQuote()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTodayQuote$Response(params?: GetTodayQuote$Params, context?: HttpContext): Observable<StrictHttpResponse<QuotesResponse>> {
    return getTodayQuote(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTodayQuote$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTodayQuote(params?: GetTodayQuote$Params, context?: HttpContext): Observable<QuotesResponse> {
    return this.getTodayQuote$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuotesResponse>): QuotesResponse => r.body)
    );
  }

}
