/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpensesResponse } from '../../models/expenses-response';

export interface FindExpenseById$Params {
  'expense-id': number;
}

export function findExpenseById(http: HttpClient, rootUrl: string, params: FindExpenseById$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpensesResponse>> {
  const rb = new RequestBuilder(rootUrl, findExpenseById.PATH, 'get');
  if (params) {
    rb.path('expense-id', params['expense-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpensesResponse>;
    })
  );
}

findExpenseById.PATH = '/expenses/{expense-id}';
