/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoryResponse } from '../../models/story-response';

export interface FindStoryById$Params {
  'story-id': number;
}

export function findStoryById(http: HttpClient, rootUrl: string, params: FindStoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<StoryResponse>> {
  const rb = new RequestBuilder(rootUrl, findStoryById.PATH, 'get');
  if (params) {
    rb.path('story-id', params['story-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StoryResponse>;
    })
  );
}

findStoryById.PATH = '/story/{story-id}';
