/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoryResponse } from '../../models/story-response';

export interface Toggle$Params {
  'story-id': number;
  reactionType: 'LIKE';
}

export function toggle(http: HttpClient, rootUrl: string, params: Toggle$Params, context?: HttpContext): Observable<StrictHttpResponse<StoryResponse>> {
  const rb = new RequestBuilder(rootUrl, toggle.PATH, 'post');
  if (params) {
    rb.path('story-id', params['story-id'], {});
    rb.path('reactionType', params.reactionType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StoryResponse>;
    })
  );
}

toggle.PATH = '/story/toggle/{story-id}/reaction/{reactionType}';
