/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportResponse } from '../../models/report-response';

export interface GetReportsByYear$Params {
  'report-year': number;
}

export function getReportsByYear(http: HttpClient, rootUrl: string, params: GetReportsByYear$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReportResponse>>> {
  const rb = new RequestBuilder(rootUrl, getReportsByYear.PATH, 'get');
  if (params) {
    rb.path('report-year', params['report-year'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReportResponse>>;
    })
  );
}

getReportsByYear.PATH = '/report/reports/{report-year}';
