/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportResponse } from '../../models/report-response';

export interface GetReportById$Params {
  'report-id': number;
}

export function getReportById(http: HttpClient, rootUrl: string, params: GetReportById$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportResponse>> {
  const rb = new RequestBuilder(rootUrl, getReportById.PATH, 'get');
  if (params) {
    rb.path('report-id', params['report-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportResponse>;
    })
  );
}

getReportById.PATH = '/report/report/{report-id}';
