/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GoalResponse } from '../../models/goal-response';

export interface FindGoalById$Params {
  'goal-id': number;
}

export function findGoalById(http: HttpClient, rootUrl: string, params: FindGoalById$Params, context?: HttpContext): Observable<StrictHttpResponse<GoalResponse>> {
  const rb = new RequestBuilder(rootUrl, findGoalById.PATH, 'get');
  if (params) {
    rb.path('goal-id', params['goal-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GoalResponse>;
    })
  );
}

findGoalById.PATH = '/goal/{goal-id}';
