/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Expenses } from '../models/expenses';
import { User } from '../models/user';
export interface Budget {
  amount?: number;
  createdBy?: number;
  createdDate?: string;
  description?: string;
  expenses?: Array<Expenses>;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  limitAmount?: number;
  name?: string;
  owner?: User;
  remainingAmount?: number;
  targetAmount?: number;
  usedAmount?: number;
}
