/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetResponse {
  amount?: number;
  availableBalance?: number;
  description?: string;
  endDate?: string;
  id?: number;
  limitAmount?: number;
  name?: string;
  owner?: string;
  remainingAmount?: number;
  startDate?: string;
  targetAmount?: number;
  totalBudget?: number;
  usedAmount?: number;
}
