/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentResponse {
  comment?: string;
  creationDate?: string;
  flaggedReason?: string;
  id?: number;
  isActive?: boolean;
  isEdited?: boolean;
  isFlagged?: boolean;
  lastUpdateDate?: string;
  numberOfDislikes?: number;
  numberOfLikes?: number;
  ownComment?: boolean;
  parentComment?: string;
  replies?: Array<CommentResponse>;
  story?: string;
  user?: string;
}
