/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentRequest {
  comment: string;
  flaggedReason?: string;
  id?: number;
  isActive?: boolean;
  isEdited?: boolean;
  isFlagged?: boolean;
  numberOfDislikes?: number;
  numberOfLikes?: number;
  numberOfReplies?: number;
  parentCommentId?: number;
  storyId: number;
  userId: number;
}
