/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactStateRequest {
  code: string;
  description?: string;
  id?: number;
  name: string;
}
