/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DebtResponse {
  amount?: number;
  description?: string;
  dueDate?: string;
  id?: number;
  issueDate?: string;
  name?: string;
  owner?: string;
  paid?: boolean;
  type?: string;
}
