/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DebtRequest {
  amount: number;
  description?: string;
  dueDate?: string;
  issueDate?: string;
  id?: number;
  isPaid?: boolean;
  name: string;
  type?: 'PERSONAL_LOAN' | 'MORTGAGE' | 'CREDIT_CARD' | 'STUDENT_LOAN' | 'BUSINESS_LOAN' | 'CAR_LOAN' | 'OTHER';
}
