/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpensesCategoryResponse {
  description?: string;
  iconUrl?: string;
  id?: number;
  name?: string;
  parentCategoryName?: string;
  subcategories?: Array<ExpensesCategoryResponse>;
}
