/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpensesResponse {
  amount?: number;
  budget?: string;
  category?: string;
  date?: string;
  description?: string;
  expensesType?: string;
  id?: number;
  name?: string;
  wallet?: string;
}
