/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NoteResponse } from '../models/note-response';
export interface ExpensesResponse {
  amount?: number;
  archived?: boolean;
  budget?: string;
  category?: string;
  date?: string;
  description?: string;
  expensesType?: string;
  id?: number;
  name?: string;
  notes?: Array<NoteResponse>;
  wallet?: string;
}
