/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Expenses } from '../models/expenses';
export interface ExpensesCategory {
  description?: string;
  expenses?: Array<Expenses>;
  icon_url?: string;
  id?: number;
  name?: string;
}
