/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoalRequest {
  currentAmount: number;
  description?: string;
  id?: number;
  name: string;
  startDate: string;
  targetAmount: number;
  targetDate: string;
  reached: boolean;
}
