/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
import { User } from '../models/user';
export interface Goal {
  createdBy?: number;
  createdDate?: string;
  currentAmount?: number;
  description?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  reached?: boolean;
  startDate?: string;
  targetAmount?: number;
  targetDate?: string;
  transactions?: Array<Transaction>;
  user?: User;
}
