/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoalResponse {
  currentAmount?: number;
  description?: string;
  id?: number;
  name?: string;
  owner?: string;
  reached?: boolean;
  startDate?: string;
  targetAmount?: number;
  targetDate?: string;
}
