/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeResponse {
  amount?: number;
  date?: string;
  description?: string;
  id?: number;
  incomeSource?: string;
  name?: string;
  wallet?: string;
}
