/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeSource {
  description?: string;
  icon_url?: string;
  id?: number;
  name?: string;
}
