/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncomeSourceResponse {
  description?: string;
  iconUrl?: string;
  id?: number;
  name?: string;
}
