/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoteResponse {
  content?: string;
  createdDate?: string;
  id?: number;
  title?: string;
}
