/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuotesResponse {
  author?: string;
  dateOfDisplay?: string;
  id?: number;
  quote?: string;
  quotePhoto?: string;
}
