/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuotesRequest {
  author: string;
  budgetCover?: string;
  dateOfDisplay: string;
  id?: number;
  quote: string;
}
