/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Report {
  balance?: number;
  createdBy?: number;
  createdDate?: string;
  details?: string;
  endDate?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  month?: number;
  mostSpendingMonth?: number;
  savingRate?: number;
  startDate?: string;
  totalDebt?: number;
  totalExpenses?: number;
  totalGoalsReached?: number;
  totalIncome?: number;
  totalPaidDebt?: number;
  totalUnpaidDebt?: number;
  type?: 'MONTHLY' | 'YEARLY';
  user?: User;
  year?: number;
}
