/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportResponse {
  balance?: number;
  details?: string;
  endDate?: string;
  id?: number;
  month?: number;
  mostSpendingMonth?: number;
  owner?: string;
  savingRate?: number;
  startDate?: string;
  totalExpenses?: number;
  totalGoalsReached?: number;
  totalIncome?: number;
  type?: string;
  year?: number;
}
