/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SavingResponse {
  amount?: number;
  fullName?: string;
  id?: number;
  month?: number;
  year?: number;
}
