/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoryRequest {
  archived: boolean;
  content: string;
  cover?: string;
  description?: string;
  id?: number;
  ownerId: number;
  status?: 'ARCHIVED' | 'PUBLISHED';
  title: string;
}
