/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoryResponse {
  archived?: boolean;
  content?: string;
  cover?: string;
  description?: string;
  id?: number;
  liked?: boolean;
  numberOfLikes?: number;
  owner?: string;
  status?: string;
  title?: string;
}
