/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoryResponse {
  archived?: boolean;
  comments?: Array<string>;
  content?: string;
  cover?: string;
  description?: string;
  id?: number;
  numberOfComments?: number;
  numberOfDislikes?: number;
  numberOfLikes?: number;
  owner?: string;
  status?: string;
  title?: string;
}
