/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponse {
  amount?: number;
  date?: string;
  description?: string;
  destinationWalletId?: number;
  goalId?: number;
  id?: number;
  message?: string;
  receiverId?: number;
  senderId?: number;
  sourceWalletId?: number;
  status?: string;
  transactionType?: string;
}
