/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionRequest {
  amount: number;
  description?: string;
  destinationWalletId?: number;
  goalId?: number;
  id?: number;
  message: string;
  receiverId?: number;
  sourceWalletId: number;
  transactionType: 'TRANSFER_TO_USER' | 'TRANSFER_TO_GOAL' | 'TRANSFER_TO_DEBT' | 'TRANSFER_TO_WALLET';
}
