/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Goal } from '../models/goal';
export interface Transaction {
  amount?: number;
  createdBy?: number;
  createdDate?: string;
  date?: string;
  description?: string;
  goal?: Goal;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  message?: string;
  status?: 'PENDING' | 'SUCCESS' | 'FAILED';
  transactionType?: 'TRANSFER' | 'TRANSFER_TO_GOAL' | 'TRANSFER_TO_WALLET';
}
