/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponse {
  amount?: number;
  date?: string;
  description?: string;
  destinationWallet?: string;
  goalName?: string;
  id?: number;
  message?: string;
  receiver?: string;
  sender?: string;
  sourceWallet?: string;
  status?: string;
  transactionType?: string;
}
