/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  createdAt?: string;
  dateOfBirth?: string;
  email?: string;
  firstName?: string;
  fullName?: string;
  id?: number;
  lastName?: string;
  new?: boolean;
  placeOfBirth?: string;
  role?: string;
  totalBalance?: number;
}
