/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Report } from '../models/report';
import { Role } from '../models/role';
import { Transaction } from '../models/transaction';
import { Wallet } from '../models/wallet';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  countForgetPassword?: number;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  id?: number;
  lastModifiedDate?: string;
  lastName?: string;
  lockoutTime?: string;
  loginAttempts?: number;
  name?: string;
  password?: string;
  passwordChanged?: boolean;
  receivedTransfers?: Array<Transaction>;
  report?: Report;
  roles?: Array<Role>;
  sentTransfers?: Array<Transaction>;
  totalBalance?: number;
  username?: string;
  wallets?: Array<Wallet>;
}
