/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserTransferResponse {
  firstName?: string;
  fullName?: string;
  id?: number;
  lastName?: string;
}
