/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WalletRequest {
  balance: number;
  currencyTypeId?: number;
  id?: number;
  name: string;
  totalExpenses?: number;
  totalIncome?: number;
}
