/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCommentResponse } from '../../models/page-response-comment-response';

export interface FindAllCommentsByStory$Params {
  'story-id': number;
  page?: number;
  size?: number;
}

export function findAllCommentsByStory(http: HttpClient, rootUrl: string, params: FindAllCommentsByStory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCommentResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllCommentsByStory.PATH, 'get');
  if (params) {
    rb.path('story-id', params['story-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCommentResponse>;
    })
  );
}

findAllCommentsByStory.PATH = '/comment/story/{story-id}';
