/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponse } from '../../models/comment-response';

export interface Toggle1$Params {
  'comment-id': number;
  reactionType: 'LIKE';
}

export function toggle1(http: HttpClient, rootUrl: string, params: Toggle1$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
  const rb = new RequestBuilder(rootUrl, toggle1.PATH, 'post');
  if (params) {
    rb.path('comment-id', params['comment-id'], {});
    rb.path('reactionType', params.reactionType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponse>;
    })
  );
}

toggle1.PATH = '/comment/toggle/{comment-id}/reaction/{reactionType}';
