/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WalletResponse } from '../../models/wallet-response';

export interface FindWalletById$Params {
  'wallet-id': number;
}

export function findWalletById(http: HttpClient, rootUrl: string, params: FindWalletById$Params, context?: HttpContext): Observable<StrictHttpResponse<WalletResponse>> {
  const rb = new RequestBuilder(rootUrl, findWalletById.PATH, 'get');
  if (params) {
    rb.path('wallet-id', params['wallet-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WalletResponse>;
    })
  );
}

findWalletById.PATH = '/wallet/{wallet-id}';
