/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetResponse } from '../../models/budget-response';

export interface FindBudgetById$Params {
  'budget-id': number;
}

export function findBudgetById(http: HttpClient, rootUrl: string, params: FindBudgetById$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetResponse>> {
  const rb = new RequestBuilder(rootUrl, findBudgetById.PATH, 'get');
  if (params) {
    rb.path('budget-id', params['budget-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetResponse>;
    })
  );
}

findBudgetById.PATH = '/budget/{budget-id}';
